#  This is example of TOML document

[profiles]

[profiles.alice]
rpcUrl = "$UNCHAIN_SEPOLIA_RPC_URL"
publicKey = "$ALICE_PUBLIC_KEY"

[profiles.bob]
rpcUrl = "$UNCHAIN_SEPOLIA_RPC_URL"
publicKey = "$BOB_PUBLIC_KEY"